CREATE TABLE IF NOT EXISTS `#__joomlalabs_profiles` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `catid` int unsigned NOT NULL DEFAULT 0,
  `profile_type` varchar(20) NOT NULL DEFAULT 'person',
  `display_name` varchar(255) NOT NULL,
  `alias` varchar(400) NOT NULL DEFAULT '',
  `user_id` int unsigned DEFAULT NULL,
  `access` int unsigned NOT NULL DEFAULT 1,
  `language` char(7) NOT NULL DEFAULT '*',
  `published` tinyint NOT NULL DEFAULT 0,
  `ordering` int NOT NULL DEFAULT 0,
  `created` datetime NOT NULL,
  `created_by` int unsigned NOT NULL DEFAULT 0,
  `modified` datetime DEFAULT NULL,
  `modified_by` int unsigned DEFAULT NULL,
  `checked_out` int unsigned DEFAULT NULL,
  `checked_out_time` datetime DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 1,
  `params` text,
  `metadata` text,
  PRIMARY KEY (`id`),
  KEY `idx_catid` (`catid`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_profile_type` (`profile_type`),
  KEY `idx_published` (`published`),
  UNIQUE KEY `idx_alias_catid` (`alias`(191), `catid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;
